In [ ]:
import pandas as pd 

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [6]:
df.head()


,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500


In [12]:
import numpy as np


a = np.array ([1, 8, 3, 6, 5])


a

a[2] = 10  

a 

array([ 1,  8, 10,  6,  5])

In [15]:
np.arange(0.4,10)


array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [17]:
np.linspace(0.4,1, 10)

array([0.4       , 0.46666667, 0.53333333, 0.6       , 0.66666667,
       0.73333333, 0.8       , 0.86666667, 0.93333333, 1.        ])

In [19]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
n = np.array ([[1,1,2], [3,4,5], [6,7,8], [9,10,11]])
n

array([[ 1,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
n [:,2] = [1,2,3,3]
n

array([[ 1,  1,  1],
       [ 3,  4,  2],
       [ 6,  7,  3],
       [ 9, 10,  3]])

In [30]:
np.random.seed(2)
np.random.rand(2,4)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097]])

In [31]:
np.random.seed(2)
np.random.randn(2,4)

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737,  0.50288142, -1.24528809]])

In [34]:
np.random.seed(2)
np.random.randint(low = 1, high = 10, size = (2,4))


array([[9, 9, 7, 3],
       [9, 8, 3, 2]])

In [35]:
n + 1


array([[ 2,  2,  2],
       [ 4,  5,  3],
       [ 7,  8,  4],
       [10, 11,  4]])

In [39]:
d = n * 2 -3
d


array([[-1, -1, -1],
       [ 3,  5,  1],
       [ 9, 11,  3],
       [15, 17,  3]])

In [ ]:
n + d 

array([[ 0,  0,  0],
       [ 6,  9,  3],
       [15, 18,  6],
       [24, 27,  6]])

In [42]:
d <= 2

array([[ True,  True,  True],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [43]:
d


array([[-1, -1, -1],
       [ 3,  5,  1],
       [ 9, 11,  3],
       [15, 17,  3]])

In [45]:
n[n > d ]

array([1, 1, 1, 2])

In [46]:
n.sum()


np.int64(50)

In [47]:
n.std()


np.float64(2.9953667926019047)

In [48]:
u = np.array ([1, 2, 3])
v = np.array ([4, 5, 6])
u + v

array([5, 7, 9])

In [49]:
def vector_vector_multiply(u, v):
    assert u.shape[0] == v.shape[0]

    n =u.shape[0]
    result = 0
    for i in range(n):
        result = result +u[i] * v[i]
    return result

In [50]:
vector_vector_multiply(u, v)

np.int64(32)

In [51]:
u.dot(v)

np.int64(32)